extends Node
## Todos os valores de calibragem do jogo num lugar só.
## Fonte: docs/04-game-design-floresta.md, seção 49.
## Para calibrar, mude o número aqui e rode o jogo de novo (F5).
## Distâncias em px (base 1920 × 1080), velocidades em px/s, tempos em segundos.

# --- Escala ---
const TILE := 48.0
const ALTURA_TAMANHO_3 := 150.0

# --- Padrão do jogo ---
const CAMINHADA_PADRAO := 300.0
const DASH_COMPRIMENTO_PADRAO := 240.0
const DASH_VELOCIDADE_PADRAO := 1200.0
const GOLPE_DURACAO_PADRAO := 0.20
const KNOCKBACK_PADRAO := 48.0
const STAMINA_RECUPERACAO_PADRAO := 3.0  # segundos por unidade
const STAMINA_MAXIMA := 4
const INTERACAO_DISTANCIA := ALTURA_TAMANHO_3 / 2.0

# --- Homem-gato: multiplicadores do game design ---
const GATO_ALTURA := 125.0
const GATO_RAIO_HITBOX := 30.0
const GATO_VIDA := 10
const GATO_MULT_CAMINHADA := 1.3
const GATO_MULT_DASH_COMPRIMENTO := 1.3
const GATO_MULT_DASH_VELOCIDADE := 2.0
const GATO_MULT_ROLAMENTO_COMPRIMENTO := 0.8
const GATO_MULT_ROLAMENTO_VELOCIDADE := 1.0
const GATO_MULT_STAMINA := 1.5
const GATO_MULT_GOLPE_DURACAO := 1.3
const GATO_ROLAMENTOS_GRATIS := 2
const GATO_ROLAMENTO_JANELA := 4.0
const GATO_ALCANCE_ATAQUE := 60.0
const GATO_DANO_GARRA := 1
const GATO_DANO_ESPADA := 2
const GATO_DANO_DASH := 2
const GATO_PARRY_JANELA := 0.2
const GATO_PARRY_RECUPERACAO := 0.4
const GATO_PARRY_ATORDOAMENTO := 1.0

# --- Homem-gato: valores resultantes ---
const GATO_CAMINHADA := CAMINHADA_PADRAO * GATO_MULT_CAMINHADA  # 390
const GATO_DASH_COMPRIMENTO := DASH_COMPRIMENTO_PADRAO * GATO_MULT_DASH_COMPRIMENTO  # 312
const GATO_DASH_VELOCIDADE := DASH_VELOCIDADE_PADRAO * GATO_MULT_DASH_VELOCIDADE  # 2400
const GATO_ROLAMENTO_COMPRIMENTO := DASH_COMPRIMENTO_PADRAO * GATO_MULT_ROLAMENTO_COMPRIMENTO  # 192
const GATO_ROLAMENTO_VELOCIDADE := DASH_VELOCIDADE_PADRAO * GATO_MULT_ROLAMENTO_VELOCIDADE  # 1200
const GATO_STAMINA_RECUPERACAO := STAMINA_RECUPERACAO_PADRAO / GATO_MULT_STAMINA  # 2 s por unidade
const GATO_GOLPE_DURACAO := GOLPE_DURACAO_PADRAO * GATO_MULT_GOLPE_DURACAO  # 0,26
const GATO_INTERVALO_GOLPE_1_2 := GATO_GOLPE_DURACAO * 0.5  # 0,13
const GATO_INTERVALO_GOLPE_2_3 := GATO_GOLPE_DURACAO * 1.0  # 0,26
const GATO_PARRY_KNOCKBACK := DASH_COMPRIMENTO_PADRAO  # 240

# --- Sapos ---
const SAPO_VIDA := 3
const SAPO_HITBOX := Vector2(54.0, 42.0)
const SAPO_SALTO_COMPRIMENTO := DASH_COMPRIMENTO_PADRAO * 0.5  # 120
const SAPO_SALTO_VELOCIDADE := DASH_VELOCIDADE_PADRAO  # 1200
const SAPO_LINGUA_ALCANCE := DASH_COMPRIMENTO_PADRAO * 0.5  # 120
const SAPO_LINGUA_VELOCIDADE := DASH_VELOCIDADE_PADRAO  # 1200
const SAPO_PERCEPCAO := 600.0
const SAPO_ZONA_PROXIMA := 120.0
const SAPO_ZONA_INTERMEDIARIA := 240.0
